### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by ngs428** [Blavkentropy1/Ban-SoulseekLeechers#7]
On Nicotine 3.3.5 and 3.3.6 I get the message below when I attempt to checkmark the plugin to activate it. 
I downloaded the files below and added them to the proper plugins folder.  Thoughts?  

![ss](https://github.com/user-attachments/assets/ce6f8de6-f9df-423e-b13e-9494033c32a1)

2024-10-18 06:59:05 Unable to load plugin Ban-SoulseekLeechers
Traceback (most recent call last):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/pluginsystem.py", line 465, in _import_plugin_instance
  File "C:/msys64/clang64/lib/python3.11/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pynicotine.plugins.Ban-SoulseekLeechers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/pluginsystem.py", line 522, in enable_plugin
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/pluginsystem.py", line 479, in _import_plugin_instance
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1078, in get_code
  File "<frozen importlib._bootstrap_external>", line 1008, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\nicsc\AppData\Roaming\nicotine\plugins\Ban-SoulseekLeechers\__init__.py", line 103
    <title>Ban-SoulseekLeechers/Ban-SoulseekLeechers/__init__.py at main · Blavkentropy1/Ban-SoulseekLeechers</title>
                                                                         ^
SyntaxError: invalid character '·' (U+00B7)

**Comment by minicoz** [comment]
my plugins folder organization is 

nictoine > plugins > Ban-SoulseekLeechers > files (\__init\__.py).

and it works for me. 
is the folder named "Ban-SoulseekLeechers" ?

**Comment by ngs428** [comment]
Yes, the folder is named the same as you have it.  

![ss2](https://github.com/user-attachments/assets/506a64b5-ea4d-416b-9550-b4bcaccfceea)

**Comment by Blavkentropy1** [comment]
Good to hear. 
Maybe the original .txt file was slightly cut off, or in a non-standard text format?

**Comment by ngs428** [comment]
> Good to hear. Maybe the original .txt file was slightly cut off, or in a non-standard text format?

Possibly.  Glad it is working now.   Thanks for your work on this!
